### ISSUE TITLE
How can I open an svg file and have snap.svg and snap.svg.zpd use it?

### ISSUE THREAD

**Issue by khovorka** [huei90/snap.svg.zpd#25] opened 2015-01-24 06:56 UTC
Hello,

I am trying to open an svg file that I saved out of snap.svg and I can save and load the file.
However, I can't do anything with it. I use the following s = Snap('#svg2');
to create the s variable. then at some poing I use s = '' or s = undefined (I tried both)
then I remove the entire SVG section and of course all content using jQuery, then I load the svg
file and add the content where it should be and it displays perfectly. However, I get a message
that s is null even after using s = Snap('#svg2') again to reintialize the variable after the
contect has successfully loaded.

Here  is the code block:
              s = undefined;
              $('#svg2').remove();
              $('#workspace').load("uploads/test.svg");
              var s = Snap("#svg2");
              s.zpd('init');
              s.zpd({ drag: false });

I don't know how to resolved this and be able to continue working with the file I loaded in so
Snap.svg.

All help is appreciated as I really need to have this working asap.

Kim H.

**Comment by khovorka** [comment] 2015-01-24 07:01
Ok, I solved the issue. It was timing related and by using a callback that was all I had to do.
Thanks,
Kim H.

**Comment by khovorka** [comment] 2015-01-24 07:07
Ok, I was premature on a bit. I have the file load and I can now zoom in, however, I can not edit anything at all. It is all frozen and so if you have a fix for that I would be happy to know what it is.
I am doing a s.zpd('destroy'); and s.zpd('init');

Thanks,
Kim H.

**Comment by khovorka** [comment] 2015-01-24 07:14
It appears that the issue is a 2nd <g iid="snapsvg-zpd-Si5amhels0" transform="matrix(1,0,0,1,0,0)">
that is inserted and it envelopes the first <g> tag causing the problem. Not sure of an easy way to fix this if there are multiple <g> tags in an svg file?
Again, any assistance with this would be appreciated.

Kim H.

**Comment by tikiatua** [comment] 2015-01-24 08:23
Hi Kim,

your problem is due to mixin the jQuery and Snap.svg. You are using the load method from jQuery and querying the DOM-Element that you want jQuery to load some content into it right afterwards. This will lead to timing problems, if your svg takes just a little longer to load. 

The correct way of doing this would be like this:

```javascript
// get a DOM element to create our svg in
var drawingArea = Snap("#workspace");

// define the url to load the svg from
var url = "uploads/test.svg");

// use snap to load the svg and call the specified function after loading the svg
Snap.load(url, function(f) {

}
s = undefined;
$('#svg2').remove();
$('#workspace').load("uploads/test.svg");
var s = Snap("#svg2");
s.zpd('init');
s.zpd({ drag: false });

**Comment by khovorka** [comment] 2015-01-24 09:03
This is not working for me for whatever reason, I have an <svg> tag, but, that needs to be removed
as the .load function will load and svg file with an <svg> tag already in it. Does not make any difference? I have to save the full svg file so I can print it using Inkscape. The workspace is actually
a div tag and so that propably should not be used? Also, perhaps I did not full explain this but I need to remove the svg stuff and replace it with the file I want to work on and so that is the purpose for the load function. I am not attempting to add the svg file to something existing ,but to replace it completely. Does that make things more clear as to what I am attempting to do?
So the line var drawingArea = Snap("#workspace"); is using the id of a div tag and not an <svg> tag.

With what I tried I am now getting this error: TypeError: s.zpd is not a function;

**Comment by khovorka** [comment] 2015-01-24 09:14
So I don't want to append information I want to comletely replace the content completely.

**Comment by tikiatua** [comment] 2015-01-24 11:17
Ok. Take a look at the following code:

```html
<!-- This is your html setup -->
<div id="workspace"></div>
```

``` javascript
// load the external svg with snap.svg.js
// this will return a Snap fragment
Snap.load("test.svg", function(fragment) {
  
    // get the workspace
    var workspace = $("#workspace");
 
   // use the jquery .empty() method to clean out all previous content if necessary (optional)
   workspace.emtpy();

    // to insert the svg into the dom, we need to insert only the svg-node of the Snap fragment
    workspace.append(fragment.node);

   // create a Snap element from the inserted svg
   var snapElement = new Snap("#workspace svg");
 
   // initialize the zpd functionality
   element.zpd("init");
});

**Comment by khovorka** [comment] 2015-01-24 16:31
tikiatua,

I appreciate the help with this, however, it does not work as the snap.svg.zpd does not respond at all.
I can not even zoom in or out and when I did that with the jQuery code I had it could do that.
I am not getting any error message about undefined variables, etc.... So I don't know what is going on. I would really love to see this work. It appears all the SVG elements are exactly as they should be
so I don't know. I have a form level var s = ''; and it gets initially assign to s = Snap("#svg2");
then inside the code block to load an SVG file I put in s = undefined. Then I have
another var s = Snap("#workspace #svg2); which appears to be successful and I then do the init
with s.zpd("init"); Just nothing responds.

**Comment by khovorka** [comment] 2015-01-24 18:01
Ok, I now do have the code zoom in and out, but, I can not edit the svg content at all.  I can not
select, move, or add anything in the svg content area.
So, I suppose it is a bug in the snap.svg.zpd plugin?
Any knowledge on that issue?

**Comment by tikiatua** [comment] 2015-01-25 08:19
Dear @khovorka, did you read the subtitle of the snap.svg.zpd plugin?

> A zoom/pan/drag/rotate plugin for Snap.svg **(useful for view only)**

Therefore "no", it is not a bug in the plugin. It is of course possible, if you have some deeper knowledge of how svg, snapsvg and the zpd-library work.

The zpd-plugin will move all content inside the svg-root-element into a group tag (g) and apply a transformation to the group tag to enable the pan and zoom functionality.

If you wish to select/move or add an element, you have to handle the item inside the group instead of directly inside the svg-root-element.

**Comment by tikiatua** [comment] 2015-01-25 08:30
See the following code for an example (using jquery as additional library):

```javascript
// load the external svg with snap.svg.js
// this will return a Snap fragment
Snap.load("test.svg", function(fragment) {

    // get the workspace
    var workspace = $("#workspace");

   // use the jquery .empty() method to clean out all previous content if necessary (optional)
   workspace.emtpy();

    // to insert the svg into the dom, we need to insert only the svg-node of the Snap fragment
    workspace.append(fragment.node);

   // create a Snap element from the inserted svg
   var snapElement = new Snap("#workspace svg");

   // initialize the zpd functionality
   snapElement.zpd("init");

   // get the zpd element inside the svg
   var zpdGroup = snapElement.select("g");

   // create a new circle object
   var circle = element.circle(20,20,15).attr({
     fill: "#bada55"
   });

   // add the circle to the zpd group
   zpdGroup.add(circle);

});
```

**Comment by khovorka** [comment] 2015-01-26 19:14
I don't believe that the full meaning of the issue is being understood. I have created and saved off an SVG file and I now load it back in to snap.svg. However, I can not move or select the indiviual items
that I could do before the svg file was saved and was still in the creation process. Since the <g> tag already existed and everything else I do not see why that file should not be editable to allow selecting,moving the existing elements on the page since they are in the group that existed before saving the file?

Are you saving that I somehow have to remove the <g> tag(s) from the svg file and recreate them after loading the saved file? 

Once the file is loaded I can add New elements but I need to be able to work with the exising elements in the svg file to move, resize, delete, etc....

Thanks,
Kim H.

**Comment by tikiatua** [comment] 2015-01-26 21:10
Hi Kim,

what do you exactly mean by "I cannot move or select individual items". How are you doing this – i.e. in Inkscape or with some javascript code?

As stated earlier:
> Every element in the svg is just moved into a g-tag, to which a transformation is applied to move/zoom all elements. 

Take a look at the generated svg-source code to see what I mean. To access any element, you just have to select it as a child element of the zpd-g-tag instead of as child element of the svg-root-element.

Please refer to the svg- and snapsvg-documentation for further information. I will now close this issue, as it is not directly related to the zpd-library.

I would suggest to create a git-repository and share your code online for people to help or getting support of an experienced javascript developer nearby if you have problems getting your code to work.

**Closed by tikiatua** 2015-01-26 21:10 UTC
